name: Deploy to Google Apps Script

# Añade estos permisos para que la acción pueda obtener un token de GitHub
permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. El nuevo paso de autenticación SIN LLAVES
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/290718974725/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@clasp-469712.iam.gserviceaccount.com'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Clasp
        run: npm install -g @google/clasp@latest

      # 2. Ya no se necesita 'clasp login'
      - name: Push to Apps Script
        run: clasp push -f