name: Deploy to Google Apps Script

permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/290718974725/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@clasp-469712.iam.gserviceaccount.com'
          create_credentials_file: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # --- LÍNEA MODIFICADA ---
      # Forzamos la instalación de una versión estable conocida
      - name: Install a Stable Version of Clasp
        run: npm install -g @google/clasp@2.4.1
      
      - name: Login to Clasp
        run: clasp login --creds ${{ steps.auth.outputs.credentials_file_path }}

      - name: Push to Apps Script
        run: clasp push -f