name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          # Sustituí los valores entre comillas con los tuyos reales si es necesario
          workload_identity_provider: 'projects/290718974725/locations/global/workloadIdentityPools/github-pool/providers/github'
          service_account: 'github-actions-deployer@agenda-app-469712.iam.gserviceaccount.com'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install specific version of Clasp
        run: npm install -g @google/clasp@2.4.1

      - name: Create dummy .clasprc.json
        run: echo '{}' > ~/.clasprc.json

      - name: Push to Google Apps Script
        run: clasp push -f
